const carBrands = [
    'Acura',
    'Adler',
    'Alfa Romeo',
    'Alpina',
    'Alpine',
    'AM General',
    'AMC',
    'Ariel',
    'Aro',
    'Asia',
    'Aston Martin',
    'Audi',
    'Austin',
    'Autobianchi',
    'Bajaj',
    'Baltijas Dzips',
    'Batmobile',
    'Beijing',
    'Bentley',
    'Bertone',
    'Bilenkin',
    'Bitter',
    'BMW',
    'Borgward',
    'Brabus',
    'Bricklin',
    'Brilliance',
    'Bristol',
    'Bufori',
    'Bugatti',
    'Buick',
    'BYD',
    'Byvin',
    'Cadillac',
    'Callaway',
    'Carbodies',
    'Caterham',
    'Changan',
    'ChangFeng',
    'Chery',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Cizeta',
    'Coggiola',
    'Dacia',
    'Dadi',
    'Daewoo2',
    'Daihatsu',
    'Daimler',
    'Datsun',
    'De Tomaso',
    'Delage',
    'DeLorean',
    'Derways',
    'DeSoto',
    'Dodge',
    'DongFeng',
    'Doninvest',
    'Donkervoort',
    'DS',
    'E-Car',
    'Eagle',
    'Eagle Cars',
    'Ecomotors',
    'Excalibur',
    'FAW',
    'Ferrari',
    'Fiat',
    'Fisker',
    'Ford',
    'Foton',
    'FSO',
    'Fuqi',
    'Geely',
    'Genesis',
    'Geo',
    'GMC',
    'Gonow',
    'Gordon',
    'Great Wall',
    'Hafei',
    'Haima',
    'Hanomag',
    'Haval',
    'Hawtai',
    'Hindustan',
    'Hispano-Suiza',
    'Holden',
    'Honda',
    'HuangHai',
    'Hudson',
    'Hummer',
    'Hyundai',
    'Infiniti',
    'Innocenti',
    'Invicta',
    'Iran Khodro',
    'Isdera',
    'Isuzu',
    'JAC',
    'Jaguar',
    'Jeep',
    'Jensen',
    'JMC',
    'Kia',
    'Koenigsegg',
    'KTM AG',
    'LADA',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'Landwind',
    'Lexus',
    'Liebao Motor',
    'Lifan',
    'Lincoln',
    'Lotus',
    'LTI',
    'Luxgen',
    'Mahindra',
    'Marcos',
    'Marlin',
    'Marussia',
    'Maruti',
    'Maserati',
    'Maybach',
    'Mazda',
    'McLare1',
    'Mega',
    'Mercedes-Benz',
    'Mercury',
    'Metrocab',
    'MG',
    'Microcar',
    'Minelli',
    'MINI',
    'Mitsubishi',
    'Mitsuoka',
    'Morgan',
    'Morris',
    'Nissan',
    'Noble',
    'Oldsmobile',
    'Opel',
    'Osca',
    'Packard',
    'Pagani',
    'Panoz',
    'Perodua',
    'Peugeot',
    'Plymouth',
    'Pontiac',
    'Porsche',
    'Premier',
    'Proton',
    'PUCH',
    'Puma',
    'Qoros',
    'Qvale',
    'Ravon',
    'Reliant',
    'Renaissance',
    'Renault',
    'Rezvani',
    'Rimac',
    'Rolls-Royce',
    'Ronart',
    'Rover',
    'Saab',
    'Saleen',
    'Santana',
    'Saturn',
    'Scion',
    'SEAT',
    'Skoda',
    'Smart',
    'Steyr',
    'Subaru',
    'Suzuki',
    'Talbot',
    'TATA',
    'Tatra',
    'Tazzari',
    'Tesla',
    'Tianma',
    'Tianye',
    'Tofas',
    'Toyota',
    'Volkswagen',
    'Volvo',
];
const models = [
    'Alfasud',
    'Alfetta',
    'Arna',
    'Brera',
    'Disco Volante',
    'Giulia',
    'Giulietta',
    'GT',
    'GTA Coupe',
    'GTV',
    'MiTo',
    'Montreal',
    'RZ',
    'Spider',
    'Sprint',
    'Stelvio',
    'SZ',
    'Tonale',
    'Lagonda',
    'One-77',
    'Rapide',
    'Tickford Capri',
    'V12 Vantage',
    'V12 Zagato',
    'V8 Vantage',
    'V8 Zagato',
    'Vanquish',
    'Virage',
    'Vulcan',
    'Speedster',
    'A1',
    'A2',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Cabriolet',
    'Coupe',
    'e-tron',
    'Q2',
    'Q3',
    'Q5',
    'Q6',
    'Q7',
    'Q8',
    'Quattro',
    'R8',
    'S1',
    'S2',
    'S3',
    'S4',
    'S5',
    'S6',
    'S7',
    'S8',
    'TT',
    'Arnage',
    'Azure',
    'Bentayga',
    'Brooklands',
    'Continental',
    'Eight',
    'Mulsanne',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'V5',
    'Blenheim',
    'Fighter',
    'Geneva',
    'La Joya',
    'Chiron',
    'Divo',
    'LaCrosse',
    'LeSabre',
    'Limited',
    'Lucerne',
    'Park Avenue',
    'Rainer',
    'Reatta',
    'Regal',
    'Rendezvous',
    'Riviera',
    'Roadmaster',
    'Skyhawk',
    'Skylark',
    'Special',
    'DeVille',
    'DTS',
    'Eldorado',
    'ELR',
    'Escalade',
    'Fleetwood',
    'Yaoguang',
    'Alero',
    'Apache',
    'Astra',
    'Astro',
    'Avalanche',
    'Aveo',
    'Bel Air',
    'Beretta',
    'Blazer',
    'Blazer K5',
    'Bolt',
    'Bolt EUV',
    'Camaro',
    'Caprice',
    'Captiva',
    'Aspen',
    'Cirrus',
    'Concorde',
    'Cordoba',
    'Crossfire',
    'Daytona',
    'Dynasty',
    'C1',
    'C2',
    'C3',
    'C3 Aircross',
    'C3 Picasso',
    'C4',
    'C4 Aircross',
    'C4 Cactus',
    'C4 Picasso',
    'C4 SpaceTourer',
    'C5',
    'C5 Aircross',
    'C5 X',
    'Dokker',
    'Duster',
    'Jogger',
    'Lodgy',
    'Logan',
    'Nova',
    'Pick-Up',
    'Sandero',
    'Solenza',
    'Spring',
    'SuperNova',
    'City Leading',
    'Alpheon',
    'Arcadia',
    'Chairman',
    'Damas',
    'Espero',
    'Evanda',
    'G2X',
    'Gentra',
    'Kalos',
    'Korando',
    'Lacetti',
    'Lanos',
    'Leganza',
    'LeMans',
    'Hijet',
    'Hijet Caddie',
    'Leeza',
    'Materia',
    'MAX',
    'Mebius',
    'Midget',
    'Mira',
    'Hornet',
    'Intrepid',
    'Journey',
    'Lancer',
    'Magnum',
    'Mayfair',
    'Monaco',
    'Neon',
    'Nitro',
    'Omni',
    'Polara',
    'California',
    'Daytona',
    'Dino',
    'Brava',
    'Bravo',
    'Cinquecento',
    'Coupe',
    'Croma',
    'Doblo',
    'Duna',
    'Egea',
    'Cortina',
    'Cougar',
    'Country Squire',
    'Crown Victoria',
    'Custom',
    'Econoline',
    'Econovan',
    'EcoSport',
    'Edge',
    'Equator',
    'Escape',
    'Escort',
    'Atlas',
    'Boyue',
    'Coolray',
    'Emgrand',
    'Ascot',
    'Ascot Innova',
    'Avancier',
    'Ballade',
    'Beat',
    'Breeze',
    'Brio',
    'Crider',
    'Crossroad',
    'Crosstour',
    'Domani',
    'Celesta',
    'Centennial',
    'Click',
    'Coupe',
    'Creta',
    'Custo',
    'Dynasty',
    'Elantra',
    'Elantra N',
    'Encino',
    'Entourage',
    'EON',
    'Equus',
    'Excel',
    'Q70',
    'QX30',
    'QX4',
    'QX50',
    'QX55',
    'QX56',
    'Amigo',
    'Ascender',
    'Aska',
    'Axiom',
    'Bellett',
    'Bighorn',
    'Mark 2',
    'Mark IX',
    'S-Type',
    'X-Type',
    'Comanche',
    'Commander',
    'Compass',
    'Ceed',
    'Ceed GT',
    'Cerato',
    'Clarus',
    'Concord',
    'Diablo',
    'Egoista',
    'Espada',
    'Gallardo',
    'Huracán',
    'Islero',
    'Jalpa',
    'Jarama',
    'LM001',
    'Dedra',
    'Delta',
    'Flaminia',
    'Flavia',
    'Fulvia',
    'Gamma',
    'Hyena',
    'Kappa',
    'Lambda',
    'Discovery',
    'Discovery Sport',
    'Freelander',
    'Nautilus',
    'Navigator',
    'Premiere',
    'Town Car',
    'Versailles',
    'Khamsin',
    'Kyalami',
    'Levante',
    'MC12',
    'MC20',
    'Merak',
    'Mexico',
    'Airtrek',
    'Aspire',
    'ASX',
    'Attrage',
    'Bravo',
    'Carisma',
    'Celeste',
    'Challenger',
    'Chariot',
    'Pistachio',
    'Proudia',
    'Raider',
    'RVR',
    'Sapporo',
    'Savrin',
    'Sigma',
    'Cima',
    'Clipper Rio',
    'Crew',
    'Cube',
    'Datsun',
    'Dayz',
    'Dayz Roox',
    'Dualis',
    'Elgrand',
    'Exa',
    'Achieva',
    'Alero',
    'Aurora',
    'Bravada',
    'Cutlass',
    'Manta',
    'Meriva',
    'Meriva OPC',
    'Mokka',
    'Monterey',
    'Monza',
    'Olympia',
    'Omega',
    'Bipper',
    'Expert',
    'iOn',
    'Partner',
    'Pick Up',
    'RCZ',
    'Rifter',
    'Traveller',
    'Laurentian',
    'LeMans',
    'Montana',
    'Parisienne',
    'Phoenix',
    'Solstice',
    'Boxster',
    'Carrera GT',
    'Cayenne',
    'Cayman',
    'Cayman GT4',
    'Macan',
    'Panamera',
    'Taycan',
    'Duster',
    'Espace',
    'Floride',
    'Fluence',
    'Fregate',
    'Fuego',
    'Kadjar',
    'Kangoo',
    'Kaptur',
    'Camargue',
    'Corniche',
    'Cullinan',
    'Dawn',
    'Ghost',
    'Park Ward',
    'Cordoba',
    'Exeo',
    'Fura',
    'Ibiza',
    'Ibiza Cupra',
    'Inca',
    'Leon',
    'Forman',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Kodiaq RS',
    'Octavia',
    'Octavia RS',
    'Popular',
    'Rapid',
    'Roomster',
    'Alcyone',
    'Ascent',
    'Baja',
    'Bighorn',
    'Bistro',
    'Brat',
    'BRZ',
    'Crosstrek',
    'Cultus',
    'DZire',
    'Equator',
    'Ertiga',
    'Escudo',
    'Esteem',
    'Every',
    'Forenza',
    'Fronte',
    'Grand Vitara',
    'Hustler',
    'Ignis',
    'Jimny',
    'Cavalier',
    'Celica',
    'Celsior',
    'Century',
    'Chaser',
    'Classic',
    'Comfort',
    'Supra',
    'Tacoma',
    'Tank',
    'Tercel',
    'Touring HiAce',
    'Town Ace',
    'Tundra',
    'Arteon',
    'Arteon R',
    'Atlas',
    'Atlas Cross Sport',
    'Beetle',
    'Bora',
    'Caddy',
    'California',
    'Caravelle',
    'Corrado',
    'Derby',
    'Eos',
    'EuroVan',
    'S70',
    'S80',
    'S90',
    'V40',
];

export { carBrands, models };


